# Generated by Django 5.0.4 on 2024-05-03 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
